### ISSUE TITLE
Improve "Total PPE Delivered" component

### ISSUE THREAD

**Issue by robbyoconnor** [NYCPPE/nyc-makers-vs-covid#24]
- [x] Just say "Face Shield" instead of specific design (https://github.com/NYCPPE/nyc-makers-vs-covid/commit/cd63a8958d3a62b9d760f7c93350e23c088482f1)
- [x] Text above the table to explain we can't disclose specific hospitals, but that these are hospitals, nursing homes, and EMTs
- [x] Need a header row on the table
- [x] Consider date delta (1 days ago, etc.)

**Comment by jakehlee** [comment]
cd63a8958d3a62b9d760f7c93350e23c088482f1

**Comment by robbyoconnor** [comment]
> [cd63a89](https://github.com/NYCPPE/nyc-makers-vs-covid/commit/cd63a8958d3a62b9d760f7c93350e23c088482f1) removed references to specific designs

This handled the first item. Thanks <3
