### ISSUE TITLE
Make maker resources more accessible to people just starting

### ISSUE THREAD

**Issue by robbyoconnor** [NYCPPE/nyc-makers-vs-covid#25]
- [ ] designed with doctors in mind
- [ ] cost-efficient to manufacture
- [ ] local manufacturing

**Comment by callil** [comment]
I can take this on

**Comment by robbyoconnor** [comment]
You got it! Assign yourself

**Comment by robbyoconnor** [comment]
I made a checklist so you can check off what's done

**Comment by robbyoconnor** [comment]
this is being worked on in https://github.com/NYCPPE/enablement
