### ISSUE TITLE
Add some kind of visual guide of what each item is 

### ISSUE THREAD

**Issue by robbyoconnor** [NYCPPE/nyc-makers-vs-covid#30]
This was broken out of #24 -- it was out of my wheelhouse so I figured rather than hold up that pull request, I'd break it out into its own issue

**Comment by callil** [comment]
good idea

**Comment by robbyoconnor** [comment]
This was broken out of #24 -- it was out of my wheelhouse so I figured rather than hold up that pull request, I'd break it out into its own issue
